# Lab exercise, week 3 - numpy & matplotlib basics

Contents:
- Overview of numpy arrays
- Exercises for numpy
- Exercises for plotting

## NumPy - overview

Python lists are somewhat weird creatures. In contrast to basic array types in other languages like C# and Java, they can hold objects of different types and new elements can be inserted in the middle. NumPy arrays are much more like C# arrays - all elements have the same type.

In [2]:
# by convention numpy is always imported as np
import numpy as np

### Common ways of creating numpy arrays

In [11]:
a = np.array([5, 2, 17])  # Convert a Python list into a numpy array
a

array([ 5,  2, 17])

In [4]:
# List of lists gets converted into a 2D array
np.array([[5, 7, 2],
          [9, 4, 1]])


array([[5, 7, 2],
       [9, 4, 1]])

In [6]:
np.arange(5)  # Same as Python's range() but creates a numpy array

array([0, 1, 2, 3, 4])

In [7]:
np.zeros(5)  # Create a numpy array with five elements, all set to zero

array([0., 0., 0., 0., 0.])

In [8]:
c = np.ones(7)  # Create a numpy array with five elements, all set to 1
c


array([1., 1., 1., 1., 1., 1., 1.])

In [9]:
# Array of 6 random numbers between 0 and 1
np.random.rand(6)

array([0.14654318, 0.24300736, 0.74564537, 0.58652819, 0.39433085,
       0.94389319])

In [10]:
# array with 6 random integers between 0 and 100 (not including 100 as usual)
np.random.randint(100, size=6)

array([64, 97,  1, 69, 74, 72])

### Array properties

In [11]:
b = np.array([[5, 7, 2],
              [9, 4, 1]])
b

array([[5, 7, 2],
       [9, 4, 1]])

In [12]:
# Data type of the array
a.dtype

dtype('int64')

In [13]:
# number of dimensions
b.ndim 

2

In [14]:
# array shape is a Python tuple, in this case it's (2, 3) because b is a 2 by 3 array.
b.shape

(2, 3)

In [15]:
# The total number of elements
b.size 

6

In [16]:
# Note that zeros byt default uses the float64 data type
z = np.zeros(7)
z.dtype

dtype('float64')

In [17]:
# But data type can be set explicitly, almost all numpy functions that create arrays take an optional dtype parameter
# Let's set it to an 8 bit integer
z = np.zeros(7, dtype=np.int8)  
z.dtype

dtype('int8')

## Exercises

Read section 2.2 of the book (The Basics of NumPy Arrays) and complete the tasks below.


### Numpy Array Creation

##### Convert a list into a numpy array

In [6]:
lst = [5, 3, 8, 4]
lst

[5, 3, 8, 4]

In [18]:
# your code here
x = np.array(lst)
x

array([5, 3, 8, 4])

#### What happens when you multiply a list by 3, what a about an array multiplied by 3?

In [22]:
# Feel free to add more cells
lst_times3 = lst * 3
lst_times3

[5, 3, 8, 4, 5, 3, 8, 4, 5, 3, 8, 4]

In [21]:
arrTimes3 = x * 3
arrTimes3

array([15,  9, 24, 12])

#### Create an array of 10 ones [1, 1, 1, ... ]

In [23]:
onesArr = np.ones(10)
onesArr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives [5, 5, 5, .... ]

In [27]:
fivesArr = np.ones(10) * 5
fivesArr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50 (including 50)

In [28]:
arrRange = np.arange(10, 51)
arrRange

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of 10 random numbers between 0 and 5

In [35]:
arrRand = np.random.rand(10) * 5
arrRand

array([0.20792331, 1.7123639 , 4.39704705, 0.60636814, 0.79295389,
       0.24842935, 1.76633356, 0.95208753, 4.87644137, 1.09373202])

#### Read the help for np.linspace function and create an array of 11 evenly spaced elements between 0 and 2
use `np.linspace?` or `?np.linspace` to show the help

In [37]:
np.linspace(0,2,11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

#### Create a 3 by 4 array of ones

In [46]:
ones1 = np.ones((3,4))
print(ones1)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### Create a 3 by 4 array of fives

In [47]:
fives = np.ones((3,4)) * 5
print(fives)

[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


### Array Indexing
Using the following arrays `a` and `m` for the questions below

In [52]:
a = np.arange(10,21)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [51]:
m = np.arange(1,22).reshape((3,7))
print(m)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


### Create an array containing... 
#### the first 4 elements of a

In [53]:
a1 = a[0:4]
a1

array([10, 11, 12, 13])

#### the last 3 elements of a

In [54]:
a2 = a[-3:]
a2

array([18, 19, 20])

#### The middle elements of a from 15 to 18 inclusive

In [57]:
a3 = a[5:9]
a3

array([15, 16, 17, 18])

#### The first column of m

In [58]:
m1 = m[:,0]
m1

array([ 1,  8, 15])

#### The middle row of m

In [60]:
m2 = m[1,:]
m2

array([ 8,  9, 10, 11, 12, 13, 14])

#### The left 3 columns of m

In [63]:
m3 = m[:,0:3]
print(m3)

[[ 1  2  3]
 [ 8  9 10]
 [15 16 17]]


#### The bottom-right 2 by 2 square

In [66]:
m4 = m[1:3,-2:]
print(m4)

[[13 14]
 [20 21]]


#### (bonus) every other element of a  

In [68]:
a4 = a[::2]
a4

array([10, 12, 14, 16, 18, 20])

### Array Math

#### Subtract 5 from each element of a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Create an array containing squares of all numbers from 1 to 10 (inclusive)

#### Create an array containing all powers of 2 from $2^0$ to $2^{10}$ (inclusive)

#### Same as above (powers of two), but subtract one from each element, that is $a_k = 2^k - 1$

### Bonus task
Write code that lists all available dtypes with specified number of bits 

In [104]:
# Hint
np.int8

numpy.int8

## Plotting Basics
 - Use [this tutorial](https://matplotlib.org/users/pyplot_tutorial.html) as reference when (if) you get stuck
 - Execute the cells with imports, otherwise you won't have numpy and matplotlib imported and Python will complain

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# Load weather data (take a look at that CSV file on GitHub or via Excel and note column names)
weather = np.loadtxt("OshawaWeather2016.csv", skiprows=1, delimiter=',')

In [6]:
weather.shape

(349, 5)

In [7]:
weather.dtype

dtype('float64')

#### Crate separate 1D arrays for each column (e.g: day, maxt, mint and so on)

In [ ]:
# your code here
# column name in csv file: Day,Max Temp (°C),Min Temp (°C),Mean Temp (°C),Total Precip (mm)
# day = weather[???]


#### Plot the minimum temperature as a function of day number

#### Plot the max temperature in degrees Fahrenheit

#### Plot the difference between the maximum and the minimum day temperature as a function of day number

#### Plot both, the minimum and maximum temperature on the same figure

#### Add axis labels and a legend to the plot above
Use the following functions:
 - plt.xlabel
 - plt.ylabel
 - plt.title
 - plt.legend

#### Plot the precipitation as a function of max temperature
You probably don't want a line connecting the dots.
Are there any patterns you can spot?

#### Plot the precipitation as a function of (t_max - t_min)

#### Read about plt.hist() function and plot a histogram of the maximum temperatures

In [ ]:
plt.hist?

#### Plot a histogram of the differences between the min and max temperature

#### For each day calculate the average of the 3 temperatures in the data (min max and avg)


#### Calculate the total amount of precipitation for the whole year
Does the number seem reasonable? The annual average precipitation in Toronto is 831 mm according to https://en.wikipedia.org/wiki/Geography_of_Toronto

#### Calculate the total precipitation on all odd numbered days (day 1, 3, 5 and so on)